Spring:
  application:
    name: library_management_system_api

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
app:
  security:
    token-validity:
      access-validity: 3600
      refresh-validity: 3600
    secret: ${SECURITY_SECRET};
  domain:
    name: ${DOMAIN_NAME}
    secure: ${DOMAIN_SECURE}
    same-site: ${DOMAIN_SAME_SITE}


#server:
#  port: 8080

